server:
  port: 8080
---

spring:
  profiles: default
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/petfriends?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: DogWalkerSchedule
          destination: petfriends
          contentType: application/json
        event-out:
          destination: petfriends
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    org.springframework.cloud: debug
server:
  port: 8080

---
spring:
  profiles: docker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${HOST_NAME}:3306/petfriends?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password:
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql


  cloud:
    stream:
      kafka:
        binder:
          brokers: ${HOST_NAME}:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: DogwalkerSchedule
          destination: petfriends
          contentType: application/json
        event-out:
          destination: petfriends
          contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    org.springframework.cloud: debug

  application:
    name: DogWalkerSchedule
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://34.219.82.75:9411/
